on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pyinstaller
        run: pip install -r requirements.txt pyinstaller
      - name: Build with Pyinstaller
        run: pyinstaller mtgdb.py -F
      - name: Prepare Artifacts
        run: |
          $v = ./dist/mtgdb.exe -V
          $v = ($v -split '\s+')[0]
          $arch = "${{ runner.arch }}".ToLower()
          $os = "${{ runner.os }}".ToLower()
          mkdir ./dist/mtgdb-$v-$os-$arch
          mv ./dist/mtgdb.exe ./dist/mtgdb-$v-$os-$arch/mtgdb.exe
          echo "BINARY_PATH=./dist/mtgdb-$v-$os-$arch/mtgdb.exe" >> $GITHUB_ENV
          echo "WINDOWS_RELEASE_NAME=mtgdb-$v-$os-$arch" >> ./windows-build-info.txt
          echo "WINDOWS_RELEASE_NAME=mtgdb-$v-$os-$arch" >> $GITHUB_ENV
          echo "WINDOWS_ARTIFACT_NAME=mtgdb-$v-$os-$arch.exe" >> ./windows-build-info.txt
          echo "WINDOWS_ARTIFACT_NAME=mtgdb-$v-$os-$arch.exe" >> $GITHUB_ENV
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_ARTIFACT_NAME }}
          path: ${{ env.BINARY_PATH }}
      - name: Upload Build Info Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-info.txt
          path: ./windows-build-info.txt

  package-releases:
    needs: build-windows
    runs-on: linux-latest
    steps:
      - name: Get Build Info Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-info
          pattern: '*-build-info.txt'
          merge-multiple: true
      - name: Load Build Info
        run: cat build-info/* >> $GITHUB_ENV
      - name: Download Builds
        uses: actions/download-artifact@v4
        with:
          path: builds
          pattern: mtgdb-*
          merge-multiple: true
      - name: Package Windows
        run: |
          mkdir -p dist
